packages:
  - api-gateway
  - experiment-service
  - decision-service
  - dashboard
  - integration-tests
  - packages/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
